// services/quranDataManifest.ts

// This file maps Surah numbers to dynamic import functions for their JSON data.
// This helps the bundler (esbuild) understand which files to include.

interface JsonModule {
  default: any; // Or a more specific type if all JSON files have a consistent structure
  [key: string]: any; 
}

type SurahModuleLoader = () => Promise<JsonModule | any>; // JSON can be default export or root

export const surahDataLoaders: Record<number, SurahModuleLoader> = {
  1: () => import('../assets/data/quran/surah_1.json'),
  2: () => import('../assets/data/quran/surah_2.json'),
  3: () => import('../assets/data/quran/surah_3.json'),
  4: () => import('../assets/data/quran/surah_4.json'),
  5: () => import('../assets/data/quran/surah_5.json'),
  6: () => import('../assets/data/quran/surah_6.json'),
  7: () => import('../assets/data/quran/surah_7.json'),
  8: () => import('../assets/data/quran/surah_8.json'),
  9: () => import('../assets/data/quran/surah_9.json'),
  10: () => import('../assets/data/quran/surah_10.json'),
  11: () => import('../assets/data/quran/surah_11.json'),
  12: () => import('../assets/data/quran/surah_12.json'),
  13: () => import('../assets/data/quran/surah_13.json'),
  14: () => import('../assets/data/quran/surah_14.json'),
  15: () => import('../assets/data/quran/surah_15.json'),
  16: () => import('../assets/data/quran/surah_16.json'),
  17: () => import('../assets/data/quran/surah_17.json'),
  18: () => import('../assets/data/quran/surah_18.json'),
  19: () => import('../assets/data/quran/surah_19.json'),
  20: () => import('../assets/data/quran/surah_20.json'),
  21: () => import('../assets/data/quran/surah_21.json'),
  22: () => import('../assets/data/quran/surah_22.json'),
  23: () => import('../assets/data/quran/surah_23.json'),
  24: () => import('../assets/data/quran/surah_24.json'),
  25: () => import('../assets/data/quran/surah_25.json'),
  26: () => import('../assets/data/quran/surah_26.json'),
  27: () => import('../assets/data/quran/surah_27.json'),
  28: () => import('../assets/data/quran/surah_28.json'),
  29: () => import('../assets/data/quran/surah_29.json'),
  30: () => import('../assets/data/quran/surah_30.json'),
  31: () => import('../assets/data/quran/surah_31.json'),
  32: () => import('../assets/data/quran/surah_32.json'),
  33: () => import('../assets/data/quran/surah_33.json'),
  34: () => import('../assets/data/quran/surah_34.json'),
  35: () => import('../assets/data/quran/surah_35.json'),
  36: () => import('../assets/data/quran/surah_36.json'),
  37: () => import('../assets/data/quran/surah_37.json'),
  38: () => import('../assets/data/quran/surah_38.json'),
  39: () => import('../assets/data/quran/surah_39.json'),
  40: () => import('../assets/data/quran/surah_40.json'),
  41: () => import('../assets/data/quran/surah_41.json'),
  42: () => import('../assets/data/quran/surah_42.json'),
  43: () => import('../assets/data/quran/surah_43.json'),
  44: () => import('../assets/data/quran/surah_44.json'),
  45: () => import('../assets/data/quran/surah_45.json'),
  46: () => import('../assets/data/quran/surah_46.json'),
  47: () => import('../assets/data/quran/surah_47.json'),
  48: () => import('../assets/data/quran/surah_48.json'),
  49: () => import('../assets/data/quran/surah_49.json'),
  50: () => import('../assets/data/quran/surah_50.json'),
  51: () => import('../assets/data/quran/surah_51.json'),
  52: () => import('../assets/data/quran/surah_52.json'),
  53: () => import('../assets/data/quran/surah_53.json'),
  54: () => import('../assets/data/quran/surah_54.json'),
  55: () => import('../assets/data/quran/surah_55.json'),
  56: () => import('../assets/data/quran/surah_56.json'),
  57: () => import('../assets/data/quran/surah_57.json'),
  58: () => import('../assets/data/quran/surah_58.json'),
  59: () => import('../assets/data/quran/surah_59.json'),
  60: () => import('../assets/data/quran/surah_60.json'),
  61: () => import('../assets/data/quran/surah_61.json'),
  62: () => import('../assets/data/quran/surah_62.json'),
  63: () => import('../assets/data/quran/surah_63.json'),
  64: () => import('../assets/data/quran/surah_64.json'),
  65: () => import('../assets/data/quran/surah_65.json'),
  66: () => import('../assets/data/quran/surah_66.json'),
  67: () => import('../assets/data/quran/surah_67.json'),
  68: () => import('../assets/data/quran/surah_68.json'),
  69: () => import('../assets/data/quran/surah_69.json'),
  70: () => import('../assets/data/quran/surah_70.json'),
  71: () => import('../assets/data/quran/surah_71.json'),
  72: () => import('../assets/data/quran/surah_72.json'),
  73: () => import('../assets/data/quran/surah_73.json'),
  74: () => import('../assets/data/quran/surah_74.json'),
  75: () => import('../assets/data/quran/surah_75.json'),
  76: () => import('../assets/data/quran/surah_76.json'),
  77: () => import('../assets/data/quran/surah_77.json'),
  78: () => import('../assets/data/quran/surah_78.json'),
  79: () => import('../assets/data/quran/surah_79.json'),
  80: () => import('../assets/data/quran/surah_80.json'),
  81: () => import('../assets/data/quran/surah_81.json'),
  82: () => import('../assets/data/quran/surah_82.json'),
  83: () => import('../assets/data/quran/surah_83.json'),
  84: () => import('../assets/data/quran/surah_84.json'),
  85: () => import('../assets/data/quran/surah_85.json'),
  86: () => import('../assets/data/quran/surah_86.json'),
  87: () => import('../assets/data/quran/surah_87.json'),
  88: () => import('../assets/data/quran/surah_88.json'),
  89: () => import('../assets/data/quran/surah_89.json'),
  90: () => import('../assets/data/quran/surah_90.json'),
  91: () => import('../assets/data/quran/surah_91.json'),
  92: () => import('../assets/data/quran/surah_92.json'),
  93: () => import('../assets/data/quran/surah_93.json'),
  94: () => import('../assets/data/quran/surah_94.json'),
  95: () => import('../assets/data/quran/surah_95.json'),
  96: () => import('../assets/data/quran/surah_96.json'),
  97: () => import('../assets/data/quran/surah_97.json'),
  98: () => import('../assets/data/quran/surah_98.json'),
  99: () => import('../assets/data/quran/surah_99.json'),
  100: () => import('../assets/data/quran/surah_100.json'),
  101: () => import('../assets/data/quran/surah_101.json'),
  102: () => import('../assets/data/quran/surah_102.json'),
  103: () => import('../assets/data/quran/surah_103.json'),
  104: () => import('../assets/data/quran/surah_104.json'),
  105: () => import('../assets/data/quran/surah_105.json'),
  106: () => import('../assets/data/quran/surah_106.json'),
  107: () => import('../assets/data/quran/surah_107.json'),
  108: () => import('../assets/data/quran/surah_108.json'),
  109: () => import('../assets/data/quran/surah_109.json'),
  110: () => import('../assets/data/quran/surah_110.json'),
  111: () => import('../assets/data/quran/surah_111.json'),
  112: () => import('../assets/data/quran/surah_112.json'),
  113: () => import('../assets/data/quran/surah_113.json'),
  114: () => import('../assets/data/quran/surah_114.json'),
};
